kind: Secret
apiVersion: v1
metadata:
  name: elasticsearch-secret
  namespace: logging
data:
  CLOUD_ELASTICSEARCH_PASSWORD: <CLOUD_ELASTICSEARCH_DEPLOYMENT_PASSWORD>
  CLOUD_ELASTICSEARCH_USER: <CLOUD_ELASTICSEARCH_DEPLOYMENT_USER>
type: Opaque
